### ISSUE TITLE
format test

### ISSUE THREAD

**Issue by Ron-Yu** [Ron-Yu/front-end-notes#1]
# title 1
###### title 6
- list1
  - list item1
  - list **item2**
- list 2

> this is **_quote_**

`var x = 'you'`

[stackoverflow](http://stackoverflow.com/)
- [x] done
- [ ] not done

@Ron-Yu

``` css
body {
    -webkit-text-size-adjust: none;
}
```

``` javascript
function clear(style) {
  ctx.save();
  ctx.fillStyle = style || 'rgba(0,0,0,0.01)';
  ctx.fillRect(0, 0, WIDTH, HEIGHT);
  ctx.restore();
}
```
