### ISSUE TITLE
Use data-attribute to describe style state

### ISSUE THREAD

**Issue by Ron-Yu** [Ron-Yu/front-end-notes#3]
> ## 使用 data-attribute 來顯示由 javascript 所驅動的狀態
### why
- 清楚知道現在的狀態
- 立即知道這是由 javascript 所驅動的狀態
- 避免與其他或全域 css style 衝突
### What

以下分別說明 **closed** 與 **open** 兩種狀態

``` css
.menuList[data-state='closed'] {
  background-color: skyblue;
}

.menuList[data-state='open'] {
  background-color: yellow;
}
```
### How

以下說明如何驅動兩種狀態的轉換

``` javascript
const menuBtn = document.querySelector('.menu');

function toggleMenuListState(menuListSelector, closedState, openState) {
    const menuList = document.querySelector(menuListSelector);
    const supposedState = menuList.getAttribute('data-state') === openState ? closedState : openState;

    menuList.setAttribute('data-state', supposedState);
}

menuBtn.addEventListener('click', () => toggleMenuListState('.menuList', 'closed', 'open'));
```
### Thought
- source code 變得有點不直覺，需要多寫些程式碼來呈現或改變狀態
- 可讀性增加
- 如果 1 個項目有多種狀態，可以做實驗以下兩種情況哪種方式呈現會比較好

``` css
.person[data-state='groupA groupB groupE'] {
  background-color: skyblue;
}
```

``` css
.person.isGroupA.isGroupB.isGroupE {
  background-color: skyblue;
}
```
### Reference

[Stop toggling classes with JS](https://goo.gl/suUDD4)
### example

[example](https://jsbin.com/sovefuz/4/edit?js,output)
